In [23]:
import numpy as np

In [24]:
v = np.array([1,2,3])
m=np.array([[1,2,3],
            [4,5,6],
            [7,8,9]])
s=np.array(5)
print(s.ndim)
print(v.ndim)
print(m.ndim)
print(s.shape)
print(v.shape)
print(m.shape)

0
1
2
()
(3,)
(3, 3)


In [25]:
vec = np.array([1,2,3,4,5,6])
mat = vec.reshape((3,2))
mat

array([[1, 2],
       [3, 4],
       [5, 6]])

In [26]:
vec = np.array([1,2,3,4])
mat = vec.reshape((vec.shape[0],1))
mat

array([[1],
       [2],
       [3],
       [4]])

In [27]:
vec = np.array([1,2,3,4])
mat = vec[:,None]
mat

array([[1],
       [2],
       [3],
       [4]])

In [28]:
def array_reshape(arr, row:int =-1 , cols:int =-1):
    try:
        arr=np.array(arr)
        return arr.reshape(row,cols)
    except (TypeError , ValueError) as e:
        raise ValueError(f"Invalid reshape operation: {e}")
        


In [29]:
vec = [1,2,3,4,5,6]
array_reshape(vec , 2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
class c:
    x=3
o1 = c()

In [32]:
mat = np.array([[1.2,"5",6],
                [4,5,6],
                [7,8,9]])
fmat = mat.astype(np.float64)
print(fmat.dtype)
fmat

float64


array([[1.2, 5. , 6. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9. ]])